<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CSharpServer.Networking" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ActionGame.Contracts\ActionGame.Contracts.csproj" />
  </ItemGroup>
</Project>

